# Generated by Django 5.0.1 on 2025-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0005_serviceproviderprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ServiceProviderProfile',
        ),
    ]
