# Generated by Django 5.0.1 on 2025-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0007_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
