# Generated by Django 5.2.3 on 2025-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0012_rename_client_earning_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
