# Generated by Django 5.2.3 on 2025-07-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0016_customerprofile_is_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_contractor',
        ),
    ]
