# Generated by Django 5.0.1 on 2025-06-30 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('solar', 'Solar Electrician')], max_length=50)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('urgent', 'Urgent (Within 24 hours)'), ('soon', 'Soon (Within a week)'), ('flexible', 'Flexible (No specific deadline)')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='tender_images/')),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
