# Generated by Django 5.0.1 on 2025-07-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0002_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
