# Generated by Django 5.2.3 on 2025-07-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0011_earning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='client',
            new_name='client_name',
        ),
        migrations.AlterField(
            model_name='earning',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20),
        ),
    ]
