# Generated by Django 5.2.3 on 2025-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommissionZeroApp', '0015_phoneotp_remove_customerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
